### ISSUE TITLE
Properly handle "user not found"

### ISSUE THREAD

**Issue by micheljung** [FAForever/faf-java-api#112]
```
Caused by: java.lang.NullPointerException: null
	at com.faforever.api.security.FafUserDetails.<init>(FafUserDetails.java:19) ~[faf-java-api-0.5.9.1.jar:na]
	at com.faforever.api.security.FafUserDetailsService.loadUserByUsername(FafUserDetailsService.java:26) ~[faf-java-api-0.5.9.1.jar:na]
	at org.springframework.security.authentication.dao.DaoAuthenticationProvider.retrieveUser(DaoAuthenticationProvider.java:114) ~[spring-security-core-4.2.2.RELEASE.jar:4.2.2.RELEASE]
	... 51 common frames omitted
```

Because the user could not be found:
```
    return new FafUserDetails(userRepository.findOneByLoginIgnoreCase(username));
```
Should throw a `UsernameNotFoundException` instead

**Comment by Yogendra0Sharma** [comment]
@micheljung Hi, I think the method loadUserByUsername()  in FafUserDetailsService.java already throws UsernameNotFoundException.

**Comment by micheljung** [comment]
@Yogendra0Sharma it only declares it, but it needs to actually throw it if `findOneByLoginIgnoreCase()` returns null

**Comment by ahsanbagwan** [comment]
Looks like the code coverage suggests adding some tests. Is that so? Please suggest.
