### ISSUE TITLE
Changing the username

### ISSUE THREAD

**Issue by axel1200** [FAForever/faf-java-api#178]
I am using postman to change my username!
I changed it from axel12 to axel1234 and then back to axel1, but the second time did not work (it was within the 30 days).
```
{
    "errors": [
        {
            "status": "500",
            "title": "java.lang.ClassCastException",
            "detail": "java.math.BigInteger cannot be cast to java.lang.Integer"
        }
    ]
}
```

**Comment by Brutus5000** [comment]
```
java.lang.ClassCastException: java.math.BigInteger cannot be cast to java.lang.Integer
        at java.util.Optional.ifPresent(Optional.java:159)
        at com.faforever.api.user.UserService.changeLogin(UserService.java:142)
        at com.faforever.api.user.UserController.changeLogin(UserController.java:70)
        at com.faforever.api.user.UserController$$FastClassBySpringCGLIB$$694533c7.invoke(<generated>)
```
I have checked the signatures and also the database type. I have no clue where the BigInt originates.

**Comment by Brutus5000** [comment]
Interesting. MySQL's `datediff` returns a BIGINT.
