### ISSUE TITLE
Log spamed with errors

### ISSUE THREAD

**Issue by axel1200** [FAForever/faf-java-api#182]
When running faf-stack, after some while the log gets spammed with following Error:
By the way I removed the 127.0.0.1 before the ports so I can access it from outside the docker enviroment.
```
 2017-11-28 15:35:20.646 ERROR 1 --- [gistrationTask1] o.s.s.s.TaskUtils$LoggingErrorHandler    : Unexpected error occurred in scheduled task.
faf-java-api                     |
faf-java-api                     | java.lang.IllegalArgumentException: 112cd20da5a3: 112cd20da5a3: System error
faf-java-api                     |      at de.codecentric.boot.admin.services.DefaultApplicationFactory.getLocalHost(DefaultApplicationFactory.java:116)
faf-java-api                     |      at de.codecentric.boot.admin.services.DefaultApplicationFactory.getServiceHost(DefaultApplicationFactory.java:99)
faf-java-api                     |      at de.codecentric.boot.admin.services.DefaultApplicationFactory.getManagementHost(DefaultApplicationFactory.java:109)
faf-java-api                     |      at de.codecentric.boot.admin.services.DefaultApplicationFactory.getManagementUrl(DefaultApplicationFactory.java:83)
faf-java-api                     |      at de.codecentric.boot.admin.services.DefaultApplicationFactory.getHealthUrl(DefaultApplicationFactory.java:91)
faf-java-api                     |      at de.codecentric.boot.admin.services.DefaultApplicationFactory.createApplication(DefaultApplicationFactory.java:46)
faf-java-api                     |      at de.codecentric.boot.admin.services.ApplicationRegistrator.createApplication(ApplicationRegistrator.java:117)
faf-java-api                     |      at de.codecentric.boot.admin.services.ApplicationRegistrator.register(ApplicationRegistrator.java:66)
faf-java-api                     |      at de.codecentric.boot.admin.services.RegistrationApplicationListener$1.run(RegistrationApplicationListener.java:80)
faf-java-api                     |      at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
faf-java-api                     |      at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
faf-java-api                     |      at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
faf-java-api                     |      at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
faf-java-api                     |      at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
faf-java-api                     |      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
faf-java-api                     |      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
faf-java-api                     |      at java.lang.Thread.run(Thread.java:748)
faf-java-api                     | Caused by: java.net.UnknownHostException: 112cd20da5a3: 112cd20da5a3: System error
faf-java-api                     |      at java.net.InetAddress.getLocalHost(InetAddress.java:1505)
faf-java-api                     |      at de.codecentric.boot.admin.services.DefaultApplicationFactory.getLocalHost(DefaultApplicationFactory.java:114)
faf-java-api                     |      ... 16 common frames omitted
faf-java-api                     | Caused by: java.net.UnknownHostException: 112cd20da5a3: System error
faf-java-api                     |      at java.net.Inet4AddressImpl.lookupAllHostAddr(Native Method)
faf-java-api                     |      at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:928)
faf-java-api                     |      at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1323)
faf-java-api                     |      at java.net.InetAddress.getLocalHost(InetAddress.java:1500)
faf-java-api                     |      ... 17 common frames omitted```

**Comment by Brutus5000** [comment]
Haven't seen this particular error in the last year.
