### ISSUE TITLE
Clan invitation fails

### ISSUE THREAD

**Issue by micheljung** [FAForever/faf-java-api#197]
```
java.lang.IllegalArgumentException: JWT must have 3 tokens
     at org.springframework.security.jwt.JwtHelper.decode(JwtHelper.java:49)
     at org.springframework.security.jwt.JwtHelper.decodeAndVerify(JwtHelper.java:76)
     at com.faforever.api.security.JwtService.decodeAndVerify(JwtService.java:29)
     at com.faforever.api.clan.ClanService.acceptPlayerInvitationToken(ClanService.java:115)
     at com.faforever.api.clan.ClansController.joinClan(ClansController.java:102)
     at com.faforever.api.clan.ClansController$$FastClassBySpringCGLIB$$ac6caee4.invoke(<generated>)
     at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
     at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:738)
     at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
     at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99)
     at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:282)
     at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
     at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
     at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:673)
     at com.faforever.api.clan.ClansController$$EnhancerBySpringCGLIB$$993d3542.joinClan(<generated>)
     at sun.reflect.GeneratedMethodAccessor914.invoke(Unknown Source)
     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     at java.lang.reflect.Method.invoke(Method.java:498)
     at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
     at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:133)
     at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:97)
     at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827)
     at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738)
     at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
     at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:967)
     at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:901)
     at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
     at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:872)
```

Something similar happened when I changed password change API from GET to POST; Spring cut off the part after the last `.` in the URL which is why I had to set this: https://github.com/FAForever/faf-java-api/commit/34cc5494445670194652544c81ae8c9f8a305c2d#diff-b4e65a9c79da006012aec024e53742e6R31

Might give a hint. Or maybe the link just needs to be URL encoded (unlikely, JWT is url-safe AFAIK)? Or maybe the mail program just didn't detect the whole URL as link (HTML email would help).

**Comment by Brutus5000** [comment]
Closed because of stale issue.
Email clients cutting of JWTs because of the multiple dots inside is a known issue and was handled as good as possible in the email templates. Better solution requires persisted tokens.
