### ISSUE TITLE
Properly handle colons in map name 

### ISSUE THREAD

**Issue by micheljung** [FAForever/faf-java-api#222]
```
java.nio.file.NoSuchFileException: /tmp/1527357301786-0/Hexa wars -> /tmp/1527357301786-0/hexa_wars_by:_marlo/degulum.v0003
         at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
         at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
         at sun.nio.fs.UnixCopyFile.move(UnixCopyFile.java:457)
         at sun.nio.fs.UnixFileSystemProvider.move(UnixFileSystemProvider.java:262)
         at java.nio.file.Files.move(Files.java:1395)
         at com.faforever.api.map.MapService.renameFolderNameAndCorrectPathInLuaFiles(MapService.java:277)
         at com.faforever.api.map.MapService.uploadMap(MapService.java:92)
         at com.faforever.api.map.MapsController.uploadMap(MapsController.java:76)
         at com.faforever.api.map.MapsController$$FastClassBySpringCGLIB$$ac6aef88.invoke(<generated>)
```

**Comment by micheljung** [comment]
This has been fixed by https://github.com/FAForever/faf-java-api/commit/24e46d909068cbaae7f8aba0b4249de30c094d21
